name: pihole_api
description: Pi-hole API.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  html: ^0.15.0
  freezed_annotation: ^0.14.2
  clock: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.5
  fake_async: ^1.2.0
  freezed: ^0.14.2
  http_mock_adapter: ^0.3.1
  json_serializable: ^4.1.3
  test: ^1.17.9
