name: flutterhole
description: A third party Android application for the Pi-Hole® dashboard.
publish_to: none
version: 6.0.0-beta.1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.11
  pihole_api: ^0.1.6
  dio: ^4.0.4
  google_fonts: ^2.2.0
  animations: ^2.0.2
  url_launcher: ^6.0.17
  flex_color_scheme: ^4.1.1
  flutter_staggered_grid_view: ^0.6.0
  qr_code_scanner: ^0.6.1
  qr_flutter: ^4.0.0
  timeago: ^3.1.0
  package_info_plus: ^1.3.0
  in_app_review: ^2.0.3
  share_plus: ^3.0.4
  flutter_markdown: ^0.6.9
  smooth_page_indicator: ^1.0.0+2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
