name: flutterhole
description: A third party Android application for the Pi-Hole® dashboard.
publish_to: none
version: 6.0.0-beta.1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true