---
name: flutterhole_web
description: FlutterHole with preliminary web support.
publish_to: none
version: 6.0.0+3
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  intl: ^0.17.0
  package_info_plus: ^1.0.3
  url_launcher: ^6.0.3
  freezed_annotation: ^0.14.2
  dartz: ^0.10.0-nullsafety.2
  flutter_staggered_grid_view: ^0.4.0
  animations: ^2.0.0
  fl_chart: ^0.36.2
  faker: ^2.0.0-rc.2
  infinite_scroll_pagination: ^3.0.1+1
  google_fonts: ^2.1.0
  auto_route: ^2.2.0
  in_app_review: ^2.0.2
  qr_code_scanner: ^0.5.1
  logging: ^1.0.1
  timeago: ^3.1.0
  flutter_markdown: ^0.6.2
  animated_text_kit: ^4.2.1
  share_plus: ^2.1.4
  device_preview: ^0.7.3
  shared_preferences: ^2.0.6
  smooth_page_indicator: ^0.3.0-nullsafety.0
  pihole_api:
    path: ./packages/pihole_api
  refreshables:
    path: ./packages/refreshables

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  auto_route_generator: ^2.1.0
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.3
  test: ^1.16.8
  #  TODO move package dependencies to packages
  http_mock_adapter: ^0.3.1

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
